import { CaseStudy } from './types';

const slugify = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: 1, index: "01",
    title: "Gotham - Risk Decipher Intelligence",
    tags: ["Business Model Canvas", "PRD", "MVP"],
    year: "2026", duration: "3 Months", role: "Product Owner", event: "BI-OJK Hackaton x Digdaya 2026",
    description: "A risk intelligence platform detecting unsustainable fintech schemes, Ponzi patterns, and financial fraud risks.",
    context: "Over the past 5 years in Indonesia, illegal investments and scam schemes (Ponzi & Pyramid Models) have caused **losses of IDR 50–140 trillion**, impacting more than 5 million victims across 2,400+ entities. Despite financial inclusion reaching 85.10%, financial literacy remains at 49.68%, exposing a **critical gap between access and understanding** that is actively exploited.\n\nThe consequences extend beyond financial loss, with 42% of victims experiencing severe psychological distress. Notably, **68% of victims reported initial suspicion** but lacked an objective way to validate their concerns.",
    problem: "There is no **objective and structured system** to deconstruct business models and distinguish real value creation from participant-funded cash flow, resulting in unreliable risk assessment.",
    challenge: "The challenge is not about labeling entities as “legal” or “illegal”—because many do not fit cleanly into either category. If an entity is formally registered and operates under regulatory oversight, **should it be considered illegal?**\n\nMany entities meet all typical signals of legitimacy yet still operate on fundamentally unsustainable structures. They exist in a **gray zone where traditional definitions and enforcement struggle to apply.**",
    approach: "To address this, I designed **SRAF (Sustainable Risk Analysis Framework)**—a multi-dimensional framework designed to systematically analyze business models and assess their sustainability.\n\nSRAF powers an AI-driven system that deconstructs financial flows and growth mechanisms. It produces an explainable risk assessment—**not as a legal verdict**, but as a clear basis for decision-making.",
    outcome: "Create an initial MVP concept that can be tested in the market.",
    team: "Solo Founder",
    tools: ["Notion", "Jira", "Antigravity"],
    projectType: "Personal Project",
    color: "#F2F2F2",
    image: "/case-study-images/gotham-preview.png",
    slug: "gotham-risk-intelligence",
    externalLink: "https://raw.githubusercontent.com/vhendyvendira/cuddly-guacamole/main/gotham-preview.png"
  },
  {
    id: 2, index: "02",
    title: "MetaGo Coin, Film Studio - Crypto",
    tags: ["Marketing", "Strategy", "Crypto"],
    year: "2026", duration: "2 Months", role: "Product Marketing", event: "MetaGo Coin",
    description: "A crypto token powering a Web3 ecosystem where users invest in films, run studios, and earn rewards through gameplay.",
    context: "The traditional film industry has high barriers to entry—only major studios can produce films, while fans can only watch. On the other hand, the crypto world is often filled with speculators who simply \"hold and hope\" without real utility.\n\nMetaGo Coin (MGO) bridges these two worlds.",
    challenge: "the challenge is how to explain this to non-crypto boomer investors?",
    opportunity: "We see high FOMO + holding incentives as momentum to convert speculators into active builders within the ecosystem.\n\nWith the upcoming launch of the Film Tokenization Launchpad, this timing is crucial to:\n\n**Build an engaged user base from the start**\n**Create organic demand for MGO**\n**Prove that Web3 + entertainment can have real utility**",
    approach: "Film Studio is a gamified platform that enables MGO token holders to actively participate in the film production ecosystem—not just as passive investors, but as virtual cinema operators generating real value.",
    utility: "Users acquire and operate virtual cinemas, where each cinema acts as a production hub for film templates purchased from a marketplace. These templates represent different tiers of film production, each with unique cost structures, durations, and earning potentials.\n\nTo sustain production and generate rewards, users must perform periodic marketing pushes within defined intervals. These pushes function as active engagement proof, ensuring that film assets remain operational and continue producing MGO rewards.",
    strategy: "**For Traditional Investors:**\nIt's like a digital franchise business—you \"buy\" an outlet, choose products, run operations, and generate revenue. The difference? Everything happens on-chain with full transparency.\n\n**For Crypto Holders:**\nThis is no longer \"hold and pray.\" Your tokens work. Your engagement = your earnings.",
    outcome: "Increased adoption rate by 60% in the first week after launch, generating nearly 500 million in total revenue.",
    team: "CEO, 2 Product Engineer, 3 Marketing Lead",
    tools: ["Notion", "Gamma", "WhatsApp"],
    projectType: "Web3, Crypto Utility",
    color: "#C8D8FF",
    image: "/case-study-images/film-studio-metago-thumbnail.png",
    slug: "metago-coin",
    externalLink: "https://raw.githubusercontent.com/vhendyvendira/cuddly-guacamole/refs/heads/main/film-studio-metago-thumbnail.png"
  },
  {
    id: 3, index: "03",
    title: "Glance Fit - Digital Health & Fitness",
    tags: ["PRD", "UI Design", "Product Policy"],
    year: "2024", duration: "2 Months", role: "Project Manager & Design Lead", event: "SparcLabs",
    description: "A social fitness platform tracking daily habits and rewarding users with redeemable points.",
    context: "Sparc Labs is a company focused on developing crypto tokens and alternative payment infrastructure in Indonesia, built on the Solana blockchain. Its vision is to create a utility token that goes beyond speculation and delivers real use cases within the DeFi and DApps ecosystem.",
    challenge: "The primary challenge was not technological—but economic: **How might we create sustainable, real-world demand for a utility token?**",
    opportunity: "Instead of positioning the token as a speculative asset, I explored a behavior-driven model—where token value is generated through users’ daily activities.\n\nThis led to the design of Glance Fit, a digital fitness platform that transforms lifestyle actions—walking, running, sleep, and nutrition—into a continuous value loop.",
    approach: "My role extended beyond design management to shaping the system end-to-end—from experience to economic layers. Users access premium features via a **pay-with-crypto model**, positioning the token as both an incentive and a medium of exchange.",
    expansion: "To drive both user acquisition and retention, I contributed to **designing a multi-layer marketing and incentive system**. These systems are reinforced by recurring commissions, upgrade incentives, and Achievement Points (AP) as a gamification layer.",
    system: "Beneath a seemingly simple user experience lies a combination of interconnected systems, all designed with a single objective To build an ecosystem that drives user behavior while sustaining value circulation within the system.",
    outcome: "Designed an end-to-end MVP for an application with 5+ core features, including 5 product policy slides.",
    team: "Designer Team",
    tools: ["Figma", "Whimsical", "ClickUp"],
    projectType: "Client Side",
    color: "#D4F0E8",
    image: "/case-study-images/glance-fit-thumbnail.png",
    slug: "glance-fit",
    externalLink: "https://github.com/vhendyvendira/glance-fit"
  },
  {
    id: 4, index: "04",
    title: "Privy Acceleration Program - Education",
    tags: ["Program Management", "Learning Operations", "Stakeholder Management"],
    year: "2023", duration: "5 Months", role: "Project Talent Researcher", event: "Privy Acceleration Program",
    description: "A 6-month program accelerating growth and core skills for 250+ junior-to-mid product and tech team members.",
    context: "As Privy scaled its Product and Technology organization, inconsistent competency standards led to unclear career paths and uneven promotion decisions across teams.\n\nTo address this, Privy launched the Acceleration Program — an intensive initiative designed not only for development, but also to standardize competency across the organization.",
    problem: "Privy lacked a standardized competency framework across Product and Technology roles, causing inconsistent skill expectations and unclear career development paths across teams.",
    challenge: "The program was designed to deliver two key outcomes: Skill development and capability enhancement across technical and functional roles, Career growth opportunities, including promotion to higher positions with greater responsibilities, compensation, and impact",
    approach: "The program also carried a sensitive underlying reality—it effectively became a structured mechanism to evaluate and filter employees, determining who was ready to be retained and continue their journey at Privy.",
    outcome: "Drove ~IDR 1B/month OPEX reduction, enabled 80+ talent remappings, and achieved 80%+ success rate with promotions and salary growth",
    team: "Ardhi Kusuma (Manager), Afri Mimo, Dewa, & HR Team",
    tools: ["Excel", "Algobash", "Google Form", "Slack"],
    projectType: "National Program",
    color: "#df0317",
    image: "/case-study-images/privy-acc-thumbnail.png",
    videoUrl: "https://www.youtube.com/embed/MT-0AktCUaE",
    slug: "privy-acceleration",
    tracks: [
      { name: "Backend", classes: 9 },
      { name: "SQA", classes: 10 },
      { name: "Product Management", classes: 5 },
      { name: "Frontend", classes: 4 },
      { name: "UI", classes: 2 },
      { name: "Android", classes: 1 },
      { name: "iOS", classes: 1 },
      { name: "UX Writing", classes: 1 }
    ],
    externalLink: "https://github.com/vhendyvendira/privy-acceleration"
  },
  {
    id: 5, index: "05",
    title: "Is traditional TV still relevant in the Digital Age?",
    tags: ["Qualitative Research", "Data Synthesis", "UX Research Report"],
    year: "2022", duration: "2 Months", role: "UX Researcher", event: "Mentify Online Bootcamp",
    description: "A qualitative study reframing broadcast TV as a contextual companion in a digital-first world.",
    context: "Broadcast television isn’t losing relevance — it’s losing priority.\n\nTBS, a national broadcaster, has seen a steady decline in viewership among young adults (18–35). This shift isn’t driven by content quality, but by a deeper behavioral change: media is no longer consumed on schedule, but on demand — personal, flexible, and always within reach.\n\nRather than competing head-on with digital platforms, this study set out to understand **where TV still fits in people’s daily lives — and why it continues to persist.**",
    approach: "A qualitative approach to capture both real behavior and underlying motivation through two distinct phases:\n\n**Diary Study**: Real-time logging of media consumption to reveal natural, unfiltered habits.\n\n**In-Depth Interviews**: Explorations into emotional drivers, preferences, and decision-making patterns.",
    outcome: "Delivered 5 product recommendations to help TBS reposition television as a contextual, habit-driven medium — and reclaim its role in everyday life.",
    opportunity: "Instead of competing with on-demand platforms, broadcasters can win by owning ritual-based moments (morning, evening, communal time) and delivering low-effort, instantly accessible content that reinforces shared viewing experiences.",
    team: "Aldo Fernando (Partner)",
    tools: ["Figma", "Figjam", "Zoom", "Google Forms"],
    projectType: "Bootcamp Capstone Project",
    color: "#FFF0D8",
    image: "/case-study-images/tv-broadcast-thumbnail.png",
    slug: "tv-ambient",
    externalLink: "https://github.com/vhendyvendira/tv-ambient"
  },
  {
    id: 6, index: "06",
    title: "K-Shop - Social Commerce",
    tags: ["Product Management", "UX Design", "Mobile Apps"],
    year: "2022", duration: "8 months, 3 major pivots", role: "Product Designer & Co-founder", event: "K-Shop Startup",
    description: "Merging social discovery with seamless commerce to reimagine how people shop online.",
    context: "K-Shop started with a simple but ambitious idea: combine Instagram's social experience with Shopee's commerce infrastructure in one native platform. Users could discover products through authentic content from people they trust, and buy without ever leaving the app.\n\nAs both product designer and co-founder, I wasn't just designing interfaces—I was defining product strategy, making roadmap decisions, and learning (often the hard way) what it takes to ship a startup product.",
    problem: "Social commerce requires a delicate balance of community trust and high-velocity transactions, which is difficult for early-stage startups to get right.",
    challenge: "Building social commerce trust in a market where users don't buy from strangers — and early-stage startups can't afford to get retention wrong.",
    approach: "I led research and design across 3 MVP cycles, using each deployment to stress-test one hypothesis about discovery and trust. The biggest decision was deprioritizing the transaction flow in favor of the social layer — betting that purchase would follow community.",
    outcome: "Launched an early MVP with limited resources, turning early challenges into insights for continuous improvement.",
    team: "3 engineers, 1 designer",
    tools: ["Figma", "Whimsical", "Trello", "React Native", "Flutter", "Wordpress"],
    projectType: "Startup Project",
    color: "#FFE8EC",
    image: "/case-study-images/k-shop-thumbnail.png",
    slug: "k-shop",
    externalLink: "https://github.com/vhendyvendira/k-shop"
  }
].map(cs => ({ ...cs, slug: cs.slug || slugify(cs.title) }));
